version: '3.0'

services:
  mysql:
    container_name: mysql8
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=coffops@phpmyadmin
      - MYSQL_DATABASE=phpmyadmin
      - MYSQL_USER=phpmyadmin
      - MYSQL_PASSWORD=coffops@phpmyadmin
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql8
      - PMA_USER=phpmyadmin
      - PMA_PASSWORD=coffops@phpmyadmin
      - PMA_PORT=3306
